
* [[https://www.enterprisestorageforum.com/hardware/paging-and-segmentation/#:~:text=Paging%20is%20a%20computer%20memory,additional%20memory,%20called%20virtual%20memory.&text=Segmentation%20is%20a%20virtual%20process,for%20related%20data,%20called%20segments.][Paging and Segmentation]]
  - processes by which data is stored to, the retrieved from, a computer's storage disk.
** Paging
   - a computer memory management function that presents storage locations to the computer's CPU as additional memory, called virtual memory. 
   - Each piece of data needs a storage address
** Segmentation
   - a virtual process that creates variable-size address spaces in computer storage for related data, called segments.
   - This process speed retrieval.
** Managing computer memory is a basic operating system function
   - both- paging and segmentation are basic functions of the OS.
   - No system can efficiently rely on limited RAM alone. So the computer's memory
   - management unit(MMU) uses the storage disk, HDD or SSD, as virtual memory to supplement RAM

* What is Paging?
  - paging = memory management function
  - specifies storage locations to the CPU as additional memory, called virtual memory.
  - The CPU cannot directly access storage disk, so the MMU emulates memory by mapping pages to frames that are in RAM.
** Page
   - A fixed-length contiguous block of virtual memory residing on disk.
     
** Frame
   - A fixed-length contiguous block located in RAM; whose sizing is *identical* to pages.
** Physical memory
    - The computer's random access memory(RAM), typically contained in DIMM cards attached to the computer's mothereboard.
** Virtual memory
   - A portion of an HDD or SSD that is reserved to emulate RAM.
   - The MMU serves up virtual memory from disk to the CPU to reduce the workload on physical momory.
** Virtual address
   - The CPU generates a virtual address for each active process.
   - The MMU maps the virtual address to a physical location in RAM
   - and passes the address to the bus. A virtual address space is the range of
   - virtual addresses under CPU control
 
** Physical address
   - A location in RAM.
   - The physical address space is the set of all physical addresses coresponding to the
   - CPU's virtual addresses.
   - A physical address space is the range of physical addresses under MMU control.

   
* What is Segmentation?
  - A virtual process that creates address spaces of various sizes in a computer system, called segments.
  - Each segment is a different virtual address space that directly corresponds to process objects.
  - When a process executes, segmentation assigns related data into segments for taster processing.
  - The sementation function maintains a segment table that includes physical addresses of the segment, size, and other data.
  - 

    
* [[https://www.youtube.com/watch?v=bfWxAG1vUM4][Segmentation Fault]]
    
