TARGET = ExceptionHandling
comp:
	javac $(TARGET).java 
run:
	java $(TARGET)
cr:
	javac $(TARGET).java && java $(TARGET)
bb:
	javac -d . $(TARGET).java && java edu.smh.game.$(TARGET)

clean:
	rm -rf edu *.class
